### ISSUE TITLE
Unable to load mods

### ISSUE THREAD

**Issue by Roncarlos** [LinqToException/Fertilizer#1] opened 2022-12-29 21:33 UTC
Following error in the log file: 

Could not load DogFetch: System.IO.FileLoadException: Impossible de charger le fichier ou l'assembly 'file:///MyPath\mod.dll' ou une de ses dépendances. L'opération n'est pas prise en charge. (Exception de HRESULT : 0x80131515)
Nom de fichier : 'file:///I:\MyPath\mod.dll' ---> System.NotSupportedException: Tentative de chargement d'un assembly à partir d'un emplacement réseau qui aurait entraîné l'utilisation de l'assembly en mode Bac à sable (sandbox) dans les versions antérieures du .NET Framework. Cette version du .NET Framework n'activant pas la stratégie CAS par défaut, ce chargement peut être dangereux. Si ce chargement n'est pas destiné à utiliser l'assembly en mode Bac à sable (sandbox), activez le commutateur loadFromRemoteSources. Pour plus d'informations, consultez http://go.microsoft.com/fwlink/?LinkId=155569.
   à System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   à System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   à System.Reflection.Assembly.LoadFrom(String assemblyFile)
   à Fertilizer.Injector.Inject()

**Comment by Roncarlos** [comment] 2022-12-29 21:36
To fix it i did that:
https://askcodez.com/impossible-de-charger-lassembly-a-partir-de-lemplacement-reseau.html

But i suppose it's not a good idea security wise. 
Maybe the bug comes from the way you load the mod file.

**Comment by LinqToException** [comment] 2022-12-29 21:49
This is caused by the "mark of the web" functionality of Windows, where downloaded files are "tainted" and therefore have tighter restrictions placed on them.

You can solve this by right-clicking the mod dll (as described in the error message), select Properties, and then "Unblock". You'll have to repeat this with every mod downloaded from the web.

![image](https://user-images.githubusercontent.com/47725963/210013506-8fcd1954-a048-4c72-a91e-1a0f19ddc585.png)

The fix you've proposed (by changing the app config) is a bit more dangerous, as it technically could allow the game to load assemblies from anywhere (including remote places).

I've had prepared a fix for this for a while, but hadn't uploaded it (yet). Seeing as this is gaining traction, I'm releasing 1.0.1 now, which has a more verbose log message that explains how to unblock the DLLs.

**Closed as completed** 2022-12-29 23:48 UTC
